name: Build and deploy

on:
  push:
    branches: "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up SSH key
        run: |
          eval "$(ssh-agent -a /tmp/ssh_agent.sock)"
          ssh-add - <<< "${{ secrets.CLOUD9_DEPLOY_KEY }}"

      - name: Build
        id: docker_build
        uses: docker/build-push-action@v2
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        with:
          tags: cs50/ide:latest,cs50/ide:${{ github.sha }}
          ssh: default
          build-args: |
            GITHUB_SHA=${{ github.sha }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Deploy
        run: |
          # Free up disk space
          # https://github.com/actions/virtual-environments/issues/2840#issuecomment-790492173
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"

          # Upload static assets to CDN
          docker cp "$(docker create cs50/ide)":/opt/c9/packages/cs50/cdn .
          aws s3 cp --recursive cdn/ "s3://mirror.cs50.net/ide/${{ github.sha }}/"

          # Push Docker image
          docker push cs50/ide:${{ github.sha }}
          docker push cs50/ide:latest
        if: ${{ github.ref == 'refs/heads/main' }}
