name: Build and push

on:
  push:
    branches: main

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up SSH key
        run: |
          eval "$(ssh-agent -a /tmp/ssh_agent.sock)"
          ssh-add - <<< "${{ secrets.CLOUD9_DEPLOY_KEY }}"

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        with:
          push: true
          tags: cs50/ide:latest,cs50/ide:${{ github.sha }}
          ssh: default

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Upload to CDN
        run: |
          ID="$(docker create cs50/ide)"
          docker cp "$ID":/opt/c9/packages/cs50/cdn .
          aws s3 cp --recursive cdn/ "s3://mirror.cs50.net/ide/$(cat cdn/head)/"
